### ISSUE TITLE
Unparsable date

### ISSUE THREAD

**Issue by lseufer** [alsterman/wellness2tcx#1]
Hi,

First of all many thanks for this. 

Here is the error message I am receiving:

Converting wellness.json to tcx
Exception in thread "main" java.text.ParseException: Unparseable date: "20/03/2019T13:30:00Z"
	at java.base/java.text.DateFormat.parse(DateFormat.java:395)
	at wellness2tcx.helper$to_unix_time.invokeStatic(helper.cljc:7)
	at wellness2tcx.helper$to_unix_time.invoke(helper.cljc:3)
	at wellness2tcx.core$raw_data__GT_tcx_map.invokeStatic(core.cljc:75)
	at wellness2tcx.core$raw_data__GT_tcx_map.invoke(core.cljc:72)
	at wellness2tcx.core$_main.invokeStatic(core.cljc:103)
	at wellness2tcx.core$_main.invoke(core.cljc:100)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at wellness2tcx.core.main(Unknown Source)

**Comment by pescarpro** [comment]
Hi,

I get the same error.
What hour should we use.
I have a lot of old activities and a don't remeber at what time were done

C:\>java -jar d:\wellness2tcx-0.1.0-standalone.jar d:\run.json 11:30:
00 D:\run.tcx
Converting d:\run.json to tcx
Exception in thread "main" java.text.ParseException: Unparseable date: "04/03/20
19T11:30:00Z"
        at java.text.DateFormat.parse(Unknown Source)
        at wellness2tcx.helper$to_unix_time.invokeStatic(helper.cljc:7)
        at wellness2tcx.helper$to_unix_time.invoke(helper.cljc:3)
        at wellness2tcx.core$raw_data__GT_tcx_map.invokeStatic(core.cljc:75)
        at wellness2tcx.core$raw_data__GT_tcx_map.invoke(core.cljc:72)
        at wellness2tcx.core$_main.invokeStatic(core.cljc:103)
        at wellness2tcx.core$_main.invoke(core.cljc:100)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at wellness2tcx.core.main(Unknown Source)

**Comment by alsterman** [comment]
Sorry for not seeing this earlier. I forgot to turn notifications on...

Could you send me the json file and i'll have a look at it. My email is marals[at]kth.se

You could also post it in this thread.

@pescarpro @Iseufer

**Comment by pescarpro** [comment]
this is the json file from mywelness

[bike.zip](https://github.com/alsterman/wellness2tcx/files/3125173/bike.zip)
