### ISSUE TITLE
Exception in thread "main" java.lang.AssertionError: Assert failed: (re-matches #"....-..-.." %)

### ISSUE THREAD

**Issue by CodeUnit** [alsterman/wellness2tcx#8]
Hi,
I'm very happy to see a tool to generate tcx fies. But when I use your tool , I get an error message:
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
Converting training1.json to tcx
Exception in thread "main" java.lang.AssertionError: Assert failed: (re-matches #"....-..-.." %)
        at wellness2tcx.helper$date_string__GT_yyyy_MM_dd.invokeStatic(helper.cljc:23)
        at wellness2tcx.helper$date_string__GT_yyyy_MM_dd.invoke(helper.cljc:23)
        at wellness2tcx.core$raw_data__GT_tcx_map.invokeStatic(core.cljc:76)
        at wellness2tcx.core$raw_data__GT_tcx_map.invoke(core.cljc:73)
        at wellness2tcx.core$_main.invokeStatic(core.cljc:105)
        at wellness2tcx.core$_main.invoke(core.cljc:102)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at wellness2tcx.core.main(Unknown Source)

Is there a workaround or can you fix it please?

**Comment by alsterman** [comment]
Please post your file that you are trying to convert.

/Marcus

Sent from my iPhone

On 22 Jan 2020, at 08:54, CodeUnit <notifications@github.com> wrote:

﻿

Hi,
I'm very happy to see a tool to generate tcx fies. But when I use your tool , I get an error message:
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on
Converting training1.json to tcx
Exception in thread "main" java.lang.AssertionError: Assert failed: (re-matches #"....-..-.." %)
at wellness2tcx.helper$date_string__GT_yyyy_MM_dd.invokeStatic(helper.cljc:23)
at wellness2tcx.helper$date_string__GT_yyyy_MM_dd.invoke(helper.cljc:23)
at wellness2tcx.core$raw_data__GT_tcx_map.invokeStatic(core.cljc:76)
at wellness2tcx.core$raw_data__GT_tcx_map.invoke(core.cljc:73)
at wellness2tcx.core$_main.invokeStatic(core.cljc:105)
at wellness2tcx.core$_main.invoke(core.cljc:102)
at clojure.lang.AFn.applyToHelper(AFn.java:160)
at clojure.lang.AFn.applyTo(AFn.java:144)
at wellness2tcx.core.main(Unknown Source)

Is there a workaround or can you fix it please?

**Comment by CodeUnit** [comment]
Hi Marcus, thanks for your quick response. Here are the problematic data.
[data.txt](https://github.com/alsterman/wellness2tcx/files/4102817/data.txt)

**Comment by knudfrank** [comment]
Hello Marcus,
I nearly get the same error on my Windows 10 machine.
`java -jar wellness2tcx-0.1.1-standalone.jar mywellness_2020-01-31_18-24.json 18:24:00 mywellness_2020-01-31_18-24.tcx`
`Converting mywellness_2020-01-31_18-24.json to tcx
Exception in thread "main" java.lang.AssertionError: Assert failed: (re-matches #"....-..-.." %)
        at wellness2tcx.helper$date_string__GT_yyyy_MM_dd.invokeStatic(helper.cljc:23)
        at wellness2tcx.helper$date_string__GT_yyyy_MM_dd.invoke(helper.cljc:23)
        at wellness2tcx.core$raw_data__GT_tcx_map.invokeStatic(core.cljc:76)
        at wellness2tcx.core$raw_data__GT_tcx_map.invoke(core.cljc:73)
        at wellness2tcx.core$_main.invokeStatic(core.cljc:105)
        at wellness2tcx.core$_main.invoke(core.cljc:102)
        at clojure.lang.AFn.applyToHelper(AFn.java:160)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at wellness2tcx.core.main(Unknown Source)`

Here is the output from my Java version:
`java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)`

Regards,
Knud

[mywellness_2020-01-31_18-24.txt](https://github.com/alsterman/wellness2tcx/files/4804153/mywellness_2020-01-31_18-24.txt)

**Comment by knudfrank** [comment]
I have now found the error. In the test data the date is formatted in the format `YYYY-mm-dd`, whereas in the export from the german My Wellness dataset the date is formatted as `dd.mm.YYYY`. It is enough to change the date to the correct format.
Please adjust the code to also accept dates in other formats.

**Comment by Timvl494** [comment]
Love the fact that someone made time to put effort in making this!

Now I'm just trying to figure out where I have to change the date. 
I'm lost. Also I never spend any time programming or what so ever.

[intervaltraining.json](https://github.com/alsterman/wellness2tcx/files/14593518/intervaltraining.json)
